### PR TITLE
Add interactive UI exercise for implementing image dragging.

### PR DESCRIPTION
**Pull request by JoshDrake-minted**

### CODE REVIEW

**Comment by JoshDrake-minted** [comment]
@alanct-minted Let me know if you think this is a little too complex for an interview exercise. I was able to clumsily do it (which would be good enough to see intent and create discussion) in a little over 5 minutes, though I had the advantage of knowing before I started how I would do it.

**Comment by alanct-minted** [comment]
Man, that's tough. I like the concept and I think I could get behind it if you provided a little more of the JS event structure around it and just had it be mainly an exercise in manipulating CSS and keeping state, then use that as a starting point for more discussion. As it stands, it's somewhat niche to know all the events (mousedown/touchdown, mousemove/touchmove, mouseup/touchup) to pull it off, and in reality, most situations end up complex enough to just use a library. :)

**Comment by JoshDrake-minted** [comment]
I was envisioning the primary goal being that of allowing the candidate to demonstrate the ability to orchestrate multiple events for a single purpose. The manipulation of the CSS was more secondary to this, as was the opportunity to show off a very common vector for controlling an event firehouse (via debounce/throttle). I'll play around with it a bit more and see if I can figure out a way to make it more approachable for the primary goal and maybe get feedback on completion from Kia as well.

**Comment by alanct-minted** [comment]
sounds good!

**Pull request merged**
